secretGenerator:
- name: outside-aws-connection-mybucket
  literals:
  - AWS_ACCESS_KEY_ID=minioadmin
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_S3_BUCKET=mybucket
  - AWS_S3_ENDPOINT=localhost:9000
  - AWS_SECRET_ACCESS_KEY=minioadmin
